version: '3'

services:
  backend:
    image: noname4350/backend:linux-amd64
    env_file:
      - ./backend/.env
    ports:
      - "5001:5001"

  frontend:
    image: noname4350/frontend:linux-amd64
    ports:
      - "3000:3000"
