import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";

import Navbar from "~/components/navbar";

export default function Projects(){
    const [loading ,setLoading] = useState(true)
    const [user ,setUser] =useState<any>(null)
    const router = useRouter();
    useEffect(
        ()=>{

            const userData = localStorage.getItem('userData');
            if (userData) {
              //  user is signed in
                console.log('UserData from local storage:', userData);
                setUser(JSON.parse(userData))
                setLoading(false)
              }
              else{
                // go back and signin
                router.push("/")
              }
        },[]
    )
    return(
        <div>
            <Head>
                <title>DevDiaries | user</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {!loading && (<Navbar userName={user?.email} />)}
        </div>
    )
} 