name: Continuous Integration Workflow test2

on: 
  pull_request: 
    branches:
      - stage
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build project
        uses: actions/checkout@v4
        uses: actions/setup-node@v3
        with:
          node-version: 18
        run: |
          cd backend
          npm install
          docker --version
          sudo service docker start # Start Docker daemon
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} > .env
          echo TOKEN_SECRET=${{ secrets.TOKEN_SECRET }} >> .env
          echo GIT_TOKEN=${{ secrets.GIT_TOKEN }} >> .env
          docker run --name mysql-container -e MYSQL_ROOT_PASSWORD=root -p 3306:3306 -d mysql
          npx prisma migrate dev --name init npx prisma db push
          npm run postinstall
          npm run dev
          cd ..
          cd frontend
          npm run dev
        env: 
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
