name: Continuous Integration Workflow test2

on: 
  pull_request: 
    branches:
      - stage
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Build Project
        run: |
          cd backend
          npm install
          docker --version
          sudo service docker start # Start Docker daemon
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} > .env
          echo TOKEN_SECRET=${{ secrets.TOKEN_SECRET }} >> .env
          echo GIT_TOKEN=${{ secrets.GIT_TOKEN }} >> .env
          docker run --name mysql-container -e MYSQL_ROOT_PASSWORD=root -p 3306:3306 -d mysql
          retries=5
          until npx prisma migrate dev --name init npx prisma db push || [ $retries -eq 0 ]; do
            sleep 10
            retries=$((retries-1))
          done
          npm run build
          npm run postinstall
          npm run dev & # so it runs in the background
          cd ..
          cd frontend
          npm run dev
