name: Continuous Integration Workflow

on: 
  pull_request: 
    branches:
      - stage
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install packages required by project
        run: |
          cd backend
          npm install
      - name: Create .env file
        run: |
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} > .env
          echo TOKEN_SECRET=${{ secrets.TOKEN_SECRET }} >> .env
          echo GIT_TOKEN=${{ secrets.GIT_TOKEN }} >> .env
        env: 
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }
      - name: Set up Docker
        run: |
          docker --version
          sudo service docker start # Start Docker daemon
      - name: Set up database on MySQL instance
        run: |
          docker run --name mysql-container -e MYSQL_ROOT_PASSWORD=root -p 3306:3306 -d mysql
          npx prisma migrate dev --name init npx prisma db push
          npm run postinstall
      - name: Run server
        run: |
          npm run dev
      - name: Run frontend server
        run: |
          cd ..
          cd frontend
          npm run dev
