name: Continuous Integration Workflow

on: 
  pull_request: 
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Build Project
        run: |
          cd backend
          npm install
          docker --version
          sudo service docker start # Start Docker daemon
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} > .env
          echo TOKEN_SECRET=${{ secrets.TOKEN_SECRET }} >> .env
          echo GIT_TOKEN=${{ secrets.GIT_TOKEN }} >> .env
          docker run --name mysql-container -e MYSQL_ROOT_PASSWORD=root -p 3306:3306 -d mysql
          retries=5
          until npx prisma migrate dev --name init npx prisma db push || [ $retries -eq 0 ]; do
            sleep 10
            retries=$((retries-1))
          done
          npm run build
          npm run postinstall
          npm run dev &
          
      - name: Start frontend
        run: |
          cd frontend
          while ! nc -z localhost 5001; do
            sleep 1
          done
          npm install
          npm run dev &
          
      - name: Run Tests
        run: |  
          # cd ..
          cd testing
          # change this to frontend port once we start frontend tests
          while ! nc -z localhost 3306; do
            sleep 1
          done
          npm install
          npm test

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          image: noname4350/noname
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: user/app:latest

