name: Continuous Integration Workflow

on: 
  pull_request: 
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Build Project
        run: |
          cd backend
          npm install
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} > .env
          echo SHADOW_DATABASE_URL=${{ secrets.SHADOW_DATABASE_URL }} >> .env
          echo TOKEN_SECRET=${{ secrets.TOKEN_SECRET }} >> .env
          echo GIT_TOKEN=${{ secrets.GIT_TOKEN }} >> .env
          npm run build
          npm run postinstall
          npm run dev &
          
      - name: Start frontend
        run: |
          cd frontend
          while ! nc -z localhost 5001; do
            sleep 1
          done
          npm install
          npm run dev &

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Run Tests
        run: |  
          # cd ..
          cd testing
          # change this to frontend port once we start frontend tests
          while ! nc -z localhost 5001; do
            sleep 1
          done
          npm install
          npm test

